name: react-native-android-build
on:
  push:
    branches:
      - main
      - add-cicd
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      run: npm i -g yarn
      run: yarn install
      env:
        config: ${{ secrets.CONFIG }}
      run: |
        touch .env
        echo "$config" >> .env
      run: yarn run lint
  
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      run: npm i -g yarn
      run: yarn install
      env:
        config: ${{ secrets.CONFIG }}
      run: |
        touch .env
        echo "$config" >> .env
      name: Build Android
        run: cd android && ./gradlew assembleRelease