on: #8
  pull_request:
    branches: [ main ]
jobs:
  QualityChecks: # Code quality checks
    runs-on: ubuntu-latest
    env:
      config: ${{ secrets.CONFIG }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          echo 'ğŸ§ª Installing yarn ğŸ§¶'
          npm i -g yarn
      - run: |
          echo 'ğŸ”§ Installing dependencies ğŸ—'
          yarn install
          touch .env
          echo '$config' >> .env
      - run: |
          echo 'ğŸ§¹ Linting âš '
          yarn run lint
  
  Build: # BUild checks #
    runs-on: ubuntu-latest
    env:
      config: ${{ secrets.CONFIG }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          echo 'ğŸ§ª Installing yarn ğŸ§¶'
          npm i -g yarn
      - run: |
          echo 'ğŸ”§ Installing dependencies ğŸ—'
          touch .env
          echo "$config" >> .env
          yarn install
      - run: |
          echo 'ğŸ¤– Building android release ğŸ’½'
          cd android && ./gradlew assembleRelease